[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }

[rpc_endpoints]
base = "https://mainnet.base.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
